CREATE TABLE IF NOT EXISTS users (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	login VARCHAR(30) NOT NULL,
	password VARCHAR(100) NOT NULL,
	fullname VARCHAR(50),
	ts_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ts_lastlogin TIMESTAMP
);

CREATE TABLE IF NOT EXISTS movies (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	omdb_id INT,
	title VARCHAR(128) NOT NULL,
	release_year VARCHAR(4),
	ts_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ts_lastmodified TIMESTAMP
);

CREATE TABLE IF NOT EXISTS followings (
	id  INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	maven_id INT,
	follower_id INT,
	ts_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (maven_id) REFERENCES users(id),
	FOREIGN KEY (follower_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS recommendations (
	id  INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	maven_id INT,
	movie_id INT,
	ts_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (maven_id) REFERENCES users(id),
	FOREIGN KEY (movie_id) REFERENCES movies(id)
);
